
services:
  db_master:
    image: postgres:17.2
    restart: always
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    container_name: api_farmacia
    volumes:
      - ./db_data:/var/lib/postgresql/data
      